"""
Django settings for portfolioproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u^$q7!^r+i@p&%(lpzf4@^no&_h4^zl9j&-qz+9aldw_#cjc!g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myportfolio',
    'bootstrap5',
    'ckeditor',
    'ckeditor_uploader',
]

CKEDITOR_UPLOAD_PATH = "uploads/"####   Etapa 4 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolioproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolioproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Configuración de Jazzmin
JAZZMIN_SETTINGS = {
    # Título del sitio que aparece en la pestaña del navegador.
    "site_title": "",
    # Encabezado del sitio en el panel de administración.
    "site_header": "Panel de Administrador",
    # Marca o nombre del sitio que aparece en la barra de navegación.
    "site_brand": "Mi Marca",
    # Ruta relativa al logotipo que aparece en la barra de navegación.
    "site_logo": "images/logo.png",
    # Mensaje de bienvenida que aparece en la página de inicio de sesión.
    "welcome_sign": "Bienvenido Nombre del programador",
    # Modelo utilizado para la búsqueda global en el panel de administración.
    "search_model": "auth.User",
    "show_sidebar": True,  # Muestra la barra lateral del menú.
    "navigation_expanded": True,  # Expande la navegación por defecto.
    # Orden de las aplicaciones y modelos en el menú.
    "order_with_respect_to": ["auth", "books", "book.author", "book.book"],
    "icons": {  # Iconos para las aplicaciones y modelos específicos.
        # Icono para la aplicación de autenticación.
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",  # Icono para el modelo de usuario.
        "auth.Group": "fas fa-users",  # Icono para el modelo de grupos.
    },
    # Icono por defecto para las aplicaciones principales.
    "default_icon_parents": "fas fa-chevron-circle-right",
    # Icono por defecto para los modelos dentro de las aplicaciones.
    "default_icon_children": "fas fa-circle",
}

# Ajustes de la interfaz de usuario de Jazzmin
JAZZMIN_UI_TWEAKS = {
    # Clase CSS para la barra de navegación.
    "navbar": "navbar-white navbar-light",
    "theme": "slate",  # Tema de color para el panel de administración.
    "sidebar": "sidebar-dark-primary",  # Clase CSS para la barra lateral.
    # Oculta los elementos hijos cuando se colapsa la barra lateral.
    "sidebar_nav_child_hide_on_collapse": True,
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILE_DIRS = [os.path.join(BASE_DIR, 'myportfolio/static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de URL de inicio de sesión y cierre de sesión en línea 160 aprox
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
